name: "Rodrigo Masini"
logo: "images/rodrigo2.png"
output_dir: "."
navbar:
  title: "Rodrigo Masini"
  left:
    - text: "Humanized AI"
    - text: "Predictive models"
    - text: "Customer acquisition"
    - text: "Personalized projects"

  right:
    - icon: fa-github fa-lg
      href: http://github.com/rmasiniexpert
    - icon: fa-twitter fa-lg
      href: https://twitter.com/rodrigo_masini
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/in/rmasiniexpert/
output:
  html_document:
    theme: paper
    css: 'styles.css'
