title: Rodrigo Masini # your name (or website title) here
logo: "/images/rodrigo2.png" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Responsible to create a new approache for A.I. commercial products: humanized and automatated data workflow. 
  <br><br>
  Unique background and rich experience to create and manage A.I. products. 
  <br><br>
  <a href="https://docs.google.com/document/d/e/2PACX-1vTPLqBZdso7GnMgQwxJUosIewp_EzqC9NlLGgLqlZoyxurerru3wpyfvstkaRR4mg/pub">View my complete Resume</a> 
  <br>
  <a href="https://www.linkedin.com/in/rmasiniexpert/">View my LinkedIn Profile</a> 
  <br>
  <a href="https://www.twitter.com/rodrigo_masini/">View my Twitter Profile</a>
  <br>
  <a href="https://www.github.com/rmasiniexpert/">View my Github Profile</a>
  <br>
  <a href="mailto:rmasiniexpert@gmail.com">Discover a new humanized A.I.</a> 
resume: "rodrigomasini.pdf"
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
