
title:  Rodrigo Masini - AI & Decision Intelligence Engineer  # your name (or website title) here
logo: "images/rodrigo2.png" # your photo (or logo) here
  First description 
  <br><br>

  <a href="https://www.linkedin.com/in/rmasiniexpert/">View My LinkedIn Profile</a> 
  <a href="https://www.twitter.com/rodrigo_masini">View My LinkedIn Profile</a> 
  
  
theme: jekyll-theme-minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
