title: Rodrigo Masini # your name (or website title) here
logo: "/images/rodrigo2.png" # your photo (or logo) here
nav:
- name:     "Code example"
  url:      "/code"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Responsible to create a new approache for A.I. commercial products: humanized and automatated data workflow. 
  <br><br>
  Unique background and rich experience to create and manage A.I. products. 
  <br><br>
  <a href="https://www.linkedin.com/in/rmasiniexpert/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.twitter.com/rodrigo_masini/">View My Twitter Profile</a>
  <br>
  <a href="mailto:rmasiniexpert@gmail.com">Discover a new humanized A.I.</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
